// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: rpc.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerwayBackend_AllocIP_FullMethodName     = "/rpc.TerwayBackend/AllocIP"
	TerwayBackend_ReleaseIP_FullMethodName   = "/rpc.TerwayBackend/ReleaseIP"
	TerwayBackend_GetIPInfo_FullMethodName   = "/rpc.TerwayBackend/GetIPInfo"
	TerwayBackend_RecordEvent_FullMethodName = "/rpc.TerwayBackend/RecordEvent"
)

// TerwayBackendClient is the client API for TerwayBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TerwayBackendClient interface {
	AllocIP(ctx context.Context, in *AllocIPRequest, opts ...grpc.CallOption) (*AllocIPReply, error)
	ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPReply, error)
	GetIPInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoReply, error)
	RecordEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventReply, error)
}

type terwayBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewTerwayBackendClient(cc grpc.ClientConnInterface) TerwayBackendClient {
	_ = "STUB: not implemented"
	return *new(TerwayBackendClient)
}

func (c *terwayBackendClient) AllocIP(ctx context.Context, in *AllocIPRequest, opts ...grpc.CallOption) (*AllocIPReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *terwayBackendClient) ReleaseIP(ctx context.Context, in *ReleaseIPRequest, opts ...grpc.CallOption) (*ReleaseIPReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *terwayBackendClient) GetIPInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *terwayBackendClient) RecordEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TerwayBackendServer is the server API for TerwayBackend service.
// All implementations must embed UnimplementedTerwayBackendServer
// for forward compatibility.
type TerwayBackendServer interface {
	AllocIP(context.Context, *AllocIPRequest) (*AllocIPReply, error)
	ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPReply, error)
	GetIPInfo(context.Context, *GetInfoRequest) (*GetInfoReply, error)
	RecordEvent(context.Context, *EventRequest) (*EventReply, error)
	mustEmbedUnimplementedTerwayBackendServer()
}

// UnimplementedTerwayBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerwayBackendServer struct{}

func (UnimplementedTerwayBackendServer) AllocIP(context.Context, *AllocIPRequest) (*AllocIPReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTerwayBackendServer) ReleaseIP(context.Context, *ReleaseIPRequest) (*ReleaseIPReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTerwayBackendServer) GetIPInfo(context.Context, *GetInfoRequest) (*GetInfoReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTerwayBackendServer) RecordEvent(context.Context, *EventRequest) (*EventReply, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTerwayBackendServer) mustEmbedUnimplementedTerwayBackendServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedTerwayBackendServer) testEmbeddedByValue() { _ = "STUB: not implemented"; return }

// UnsafeTerwayBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerwayBackendServer will
// result in compilation errors.
type UnsafeTerwayBackendServer interface {
	mustEmbedUnimplementedTerwayBackendServer()
}

func RegisterTerwayBackendServer(s grpc.ServiceRegistrar, srv TerwayBackendServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedTerwayBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _TerwayBackend_AllocIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TerwayBackend_ReleaseIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TerwayBackend_GetIPInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TerwayBackend_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TerwayBackend_ServiceDesc is the grpc.ServiceDesc for TerwayBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerwayBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.TerwayBackend",
	HandlerType: (*TerwayBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocIP",
			Handler:    _TerwayBackend_AllocIP_Handler,
		},
		{
			MethodName: "ReleaseIP",
			Handler:    _TerwayBackend_ReleaseIP_Handler,
		},
		{
			MethodName: "GetIPInfo",
			Handler:    _TerwayBackend_GetIPInfo_Handler,
		},
		{
			MethodName: "RecordEvent",
			Handler:    _TerwayBackend_RecordEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
