// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tracing.proto

package rpc

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Placeholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholder) Reset() { _ = "STUB: not implemented"; return }

func (x *Placeholder) String() string { _ = "STUB: not implemented"; return "" }

func (*Placeholder) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type ResourcesTypesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeNames     []string               `protobuf:"bytes,1,rep,name=TypeNames,proto3" json:"TypeNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesTypesReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourcesTypesReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourcesTypesReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourcesTypesReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourcesTypesReply.ProtoReflect.Descriptor instead.
func (*ResourcesTypesReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourcesTypesReply) GetTypeNames() []string { _ = "STUB: not implemented"; return nil }

type ResourcesNamesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceNames []string               `protobuf:"bytes,1,rep,name=ResourceNames,proto3" json:"ResourceNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcesNamesReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourcesNamesReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourcesNamesReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourcesNamesReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourcesNamesReply.ProtoReflect.Descriptor instead.
func (*ResourcesNamesReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourcesNamesReply) GetResourceNames() []string { _ = "STUB: not implemented"; return nil }

type ResourceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTypeRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceTypeRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceTypeRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceTypeRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceTypeRequest.ProtoReflect.Descriptor instead.
func (*ResourceTypeRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceTypeRequest) GetName() string { _ = "STUB: not implemented"; return "" }

type ResourceTypeNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTypeNameRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceTypeNameRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceTypeNameRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceTypeNameRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceTypeNameRequest.ProtoReflect.Descriptor instead.
func (*ResourceTypeNameRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceTypeNameRequest) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceTypeNameRequest) GetName() string { _ = "STUB: not implemented"; return "" }

type ResourceExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=Args,proto3" json:"Args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceExecuteRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceExecuteRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceExecuteRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceExecuteRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceExecuteRequest.ProtoReflect.Descriptor instead.
func (*ResourceExecuteRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceExecuteRequest) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceExecuteRequest) GetName() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceExecuteRequest) GetCommand() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceExecuteRequest) GetArgs() []string { _ = "STUB: not implemented"; return nil }

type ResourceExecuteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceExecuteReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceExecuteReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceExecuteReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceExecuteReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceExecuteReply.ProtoReflect.Descriptor instead.
func (*ResourceExecuteReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceExecuteReply) GetMessage() string { _ = "STUB: not implemented"; return "" }

type MapKeyValueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapKeyValueEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *MapKeyValueEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*MapKeyValueEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *MapKeyValueEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use MapKeyValueEntry.ProtoReflect.Descriptor instead.
func (*MapKeyValueEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *MapKeyValueEntry) GetKey() string { _ = "STUB: not implemented"; return "" }

func (x *MapKeyValueEntry) GetValue() string { _ = "STUB: not implemented"; return "" }

type ResourceConfigReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*MapKeyValueEntry    `protobuf:"bytes,1,rep,name=Config,proto3" json:"Config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceConfigReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceConfigReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceConfigReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceConfigReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceConfigReply.ProtoReflect.Descriptor instead.
func (*ResourceConfigReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceConfigReply) GetConfig() []*MapKeyValueEntry {
	_ = "STUB: not implemented"
	return nil
}

type ResourceTraceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         []*MapKeyValueEntry    `protobuf:"bytes,1,rep,name=Trace,proto3" json:"Trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceTraceReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceTraceReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceTraceReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceTraceReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceTraceReply.ProtoReflect.Descriptor instead.
func (*ResourceTraceReply) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ResourceTraceReply) GetTrace() []*MapKeyValueEntry { _ = "STUB: not implemented"; return nil }

type PrefixIPAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PodId         string                 `protobuf:"bytes,2,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixIPAllocation) Reset() { _ = "STUB: not implemented"; return }

func (x *PrefixIPAllocation) String() string { _ = "STUB: not implemented"; return "" }

func (*PrefixIPAllocation) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PrefixIPAllocation) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PrefixIPAllocation.ProtoReflect.Descriptor instead.
func (*PrefixIPAllocation) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PrefixIPAllocation) GetIp() string { _ = "STUB: not implemented"; return "" }

func (x *PrefixIPAllocation) GetPodId() string { _ = "STUB: not implemented"; return "" }

type PrefixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Total         uint32                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint32                 `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Available     uint32                 `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Allocations   []*PrefixIPAllocation  `protobuf:"bytes,6,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixInfo) Reset() { _ = "STUB: not implemented"; return }

func (x *PrefixInfo) String() string { _ = "STUB: not implemented"; return "" }

func (*PrefixInfo) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PrefixInfo) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PrefixInfo.ProtoReflect.Descriptor instead.
func (*PrefixInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PrefixInfo) GetPrefix() string { _ = "STUB: not implemented"; return "" }

func (x *PrefixInfo) GetStatus() string { _ = "STUB: not implemented"; return "" }

func (x *PrefixInfo) GetTotal() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *PrefixInfo) GetUsed() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *PrefixInfo) GetAvailable() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *PrefixInfo) GetAllocations() []*PrefixIPAllocation { _ = "STUB: not implemented"; return nil }

type ResourceDBEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	EniId         string                 `protobuf:"bytes,3,opt,name=eni_id,json=eniId,proto3" json:"eni_id,omitempty"`
	EniMac        string                 `protobuf:"bytes,4,opt,name=eni_mac,json=eniMac,proto3" json:"eni_mac,omitempty"`
	Ipv4          string                 `protobuf:"bytes,5,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          string                 `protobuf:"bytes,6,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDBEntry) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceDBEntry) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceDBEntry) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceDBEntry) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceDBEntry.ProtoReflect.Descriptor instead.
func (*ResourceDBEntry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ResourceDBEntry) GetPodName() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetPodNamespace() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetEniId() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetEniMac() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetIpv4() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetIpv6() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceDBEntry) GetType() string { _ = "STUB: not implemented"; return "" }

type ResourceMapping struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NetworkInterfaceID   string                 `protobuf:"bytes,1,opt,name=NetworkInterfaceID,proto3" json:"NetworkInterfaceID,omitempty"`
	MAC                  string                 `protobuf:"bytes,2,opt,name=MAC,proto3" json:"MAC,omitempty"`
	Type                 string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	AllocInhibitExpireAt string                 `protobuf:"bytes,4,opt,name=AllocInhibitExpireAt,proto3" json:"AllocInhibitExpireAt,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Info                 []string               `protobuf:"bytes,6,rep,name=Info,proto3" json:"Info,omitempty"`
	Ipv4Prefixes         []*PrefixInfo          `protobuf:"bytes,7,rep,name=ipv4_prefixes,json=ipv4Prefixes,proto3" json:"ipv4_prefixes,omitempty"`
	Ipv6Prefixes         []*PrefixInfo          `protobuf:"bytes,8,rep,name=ipv6_prefixes,json=ipv6Prefixes,proto3" json:"ipv6_prefixes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceMapping) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceMapping) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceMapping) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceMapping) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceMapping.ProtoReflect.Descriptor instead.
func (*ResourceMapping) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ResourceMapping) GetNetworkInterfaceID() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceMapping) GetMAC() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceMapping) GetType() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceMapping) GetAllocInhibitExpireAt() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceMapping) GetStatus() string { _ = "STUB: not implemented"; return "" }

func (x *ResourceMapping) GetInfo() []string { _ = "STUB: not implemented"; return nil }

func (x *ResourceMapping) GetIpv4Prefixes() []*PrefixInfo { _ = "STUB: not implemented"; return nil }

func (x *ResourceMapping) GetIpv6Prefixes() []*PrefixInfo { _ = "STUB: not implemented"; return nil }

type ResourceMappingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*ResourceMapping     `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	ResourceDb    []*ResourceDBEntry     `protobuf:"bytes,2,rep,name=resource_db,json=resourceDb,proto3" json:"resource_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMappingReply) Reset() { _ = "STUB: not implemented"; return }

func (x *ResourceMappingReply) String() string { _ = "STUB: not implemented"; return "" }

func (*ResourceMappingReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ResourceMappingReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ResourceMappingReply.ProtoReflect.Descriptor instead.
func (*ResourceMappingReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *ResourceMappingReply) GetInfo() []*ResourceMapping { _ = "STUB: not implemented"; return nil }

func (x *ResourceMappingReply) GetResourceDb() []*ResourceDBEntry {
	_ = "STUB: not implemented"
	return nil
}

var File_tracing_proto protoreflect.FileDescriptor

const file_tracing_proto_rawDesc = "" +
	"\n" +
	"\rtracing.proto\x12\x03rpc\"\r\n" +
	"\vPlaceholder\"3\n" +
	"\x13ResourcesTypesReply\x12\x1c\n" +
	"\tTypeNames\x18\x01 \x03(\tR\tTypeNames\";\n" +
	"\x13ResourcesNamesReply\x12$\n" +
	"\rResourceNames\x18\x01 \x03(\tR\rResourceNames\")\n" +
	"\x13ResourceTypeRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"A\n" +
	"\x17ResourceTypeNameRequest\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"n\n" +
	"\x16ResourceExecuteRequest\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aCommand\x18\x03 \x01(\tR\aCommand\x12\x12\n" +
	"\x04Args\x18\x04 \x03(\tR\x04Args\"0\n" +
	"\x14ResourceExecuteReply\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\":\n" +
	"\x10MapKeyValueEntry\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"D\n" +
	"\x13ResourceConfigReply\x12-\n" +
	"\x06Config\x18\x01 \x03(\v2\x15.rpc.MapKeyValueEntryR\x06Config\"A\n" +
	"\x12ResourceTraceReply\x12+\n" +
	"\x05Trace\x18\x01 \x03(\v2\x15.rpc.MapKeyValueEntryR\x05Trace\";\n" +
	"\x12PrefixIPAllocation\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x15\n" +
	"\x06pod_id\x18\x02 \x01(\tR\x05podId\"\xbf\x01\n" +
	"\n" +
	"PrefixInfo\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05total\x18\x03 \x01(\rR\x05total\x12\x12\n" +
	"\x04used\x18\x04 \x01(\rR\x04used\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\rR\tavailable\x129\n" +
	"\vallocations\x18\x06 \x03(\v2\x17.rpc.PrefixIPAllocationR\vallocations\"\xbd\x01\n" +
	"\x0fResourceDBEntry\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x15\n" +
	"\x06eni_id\x18\x03 \x01(\tR\x05eniId\x12\x17\n" +
	"\aeni_mac\x18\x04 \x01(\tR\x06eniMac\x12\x12\n" +
	"\x04ipv4\x18\x05 \x01(\tR\x04ipv4\x12\x12\n" +
	"\x04ipv6\x18\x06 \x01(\tR\x04ipv6\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"\xb3\x02\n" +
	"\x0fResourceMapping\x12.\n" +
	"\x12NetworkInterfaceID\x18\x01 \x01(\tR\x12NetworkInterfaceID\x12\x10\n" +
	"\x03MAC\x18\x02 \x01(\tR\x03MAC\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x122\n" +
	"\x14AllocInhibitExpireAt\x18\x04 \x01(\tR\x14AllocInhibitExpireAt\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\tR\x06Status\x12\x12\n" +
	"\x04Info\x18\x06 \x03(\tR\x04Info\x124\n" +
	"\ripv4_prefixes\x18\a \x03(\v2\x0f.rpc.PrefixInfoR\fipv4Prefixes\x124\n" +
	"\ripv6_prefixes\x18\b \x03(\v2\x0f.rpc.PrefixInfoR\fipv6Prefixes\"w\n" +
	"\x14ResourceMappingReply\x12(\n" +
	"\x04info\x18\x01 \x03(\v2\x14.rpc.ResourceMappingR\x04info\x125\n" +
	"\vresource_db\x18\x02 \x03(\v2\x14.rpc.ResourceDBEntryR\n" +
	"resourceDb2\xbb\x03\n" +
	"\rTerwayTracing\x12>\n" +
	"\x10GetResourceTypes\x12\x10.rpc.Placeholder\x1a\x18.rpc.ResourcesTypesReply\x12B\n" +
	"\fGetResources\x12\x18.rpc.ResourceTypeRequest\x1a\x18.rpc.ResourcesNamesReply\x12K\n" +
	"\x11GetResourceConfig\x12\x1c.rpc.ResourceTypeNameRequest\x1a\x18.rpc.ResourceConfigReply\x12I\n" +
	"\x10GetResourceTrace\x12\x1c.rpc.ResourceTypeNameRequest\x1a\x17.rpc.ResourceTraceReply\x12K\n" +
	"\x0fResourceExecute\x12\x1b.rpc.ResourceExecuteRequest\x1a\x19.rpc.ResourceExecuteReply0\x01\x12A\n" +
	"\x12GetResourceMapping\x12\x10.rpc.Placeholder\x1a\x19.rpc.ResourceMappingReplyB\aZ\x05.;rpcb\x06proto3"

var (
	file_tracing_proto_rawDescOnce sync.Once
	file_tracing_proto_rawDescData []byte
)

func file_tracing_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_tracing_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_tracing_proto_goTypes = []any{
	(*Placeholder)(nil),             // 0: rpc.Placeholder
	(*ResourcesTypesReply)(nil),     // 1: rpc.ResourcesTypesReply
	(*ResourcesNamesReply)(nil),     // 2: rpc.ResourcesNamesReply
	(*ResourceTypeRequest)(nil),     // 3: rpc.ResourceTypeRequest
	(*ResourceTypeNameRequest)(nil), // 4: rpc.ResourceTypeNameRequest
	(*ResourceExecuteRequest)(nil),  // 5: rpc.ResourceExecuteRequest
	(*ResourceExecuteReply)(nil),    // 6: rpc.ResourceExecuteReply
	(*MapKeyValueEntry)(nil),        // 7: rpc.MapKeyValueEntry
	(*ResourceConfigReply)(nil),     // 8: rpc.ResourceConfigReply
	(*ResourceTraceReply)(nil),      // 9: rpc.ResourceTraceReply
	(*PrefixIPAllocation)(nil),      // 10: rpc.PrefixIPAllocation
	(*PrefixInfo)(nil),              // 11: rpc.PrefixInfo
	(*ResourceDBEntry)(nil),         // 12: rpc.ResourceDBEntry
	(*ResourceMapping)(nil),         // 13: rpc.ResourceMapping
	(*ResourceMappingReply)(nil),    // 14: rpc.ResourceMappingReply
}
var file_tracing_proto_depIdxs = []int32{
	7,  // 0: rpc.ResourceConfigReply.Config:type_name -> rpc.MapKeyValueEntry
	7,  // 1: rpc.ResourceTraceReply.Trace:type_name -> rpc.MapKeyValueEntry
	10, // 2: rpc.PrefixInfo.allocations:type_name -> rpc.PrefixIPAllocation
	11, // 3: rpc.ResourceMapping.ipv4_prefixes:type_name -> rpc.PrefixInfo
	11, // 4: rpc.ResourceMapping.ipv6_prefixes:type_name -> rpc.PrefixInfo
	13, // 5: rpc.ResourceMappingReply.info:type_name -> rpc.ResourceMapping
	12, // 6: rpc.ResourceMappingReply.resource_db:type_name -> rpc.ResourceDBEntry
	0,  // 7: rpc.TerwayTracing.GetResourceTypes:input_type -> rpc.Placeholder
	3,  // 8: rpc.TerwayTracing.GetResources:input_type -> rpc.ResourceTypeRequest
	4,  // 9: rpc.TerwayTracing.GetResourceConfig:input_type -> rpc.ResourceTypeNameRequest
	4,  // 10: rpc.TerwayTracing.GetResourceTrace:input_type -> rpc.ResourceTypeNameRequest
	5,  // 11: rpc.TerwayTracing.ResourceExecute:input_type -> rpc.ResourceExecuteRequest
	0,  // 12: rpc.TerwayTracing.GetResourceMapping:input_type -> rpc.Placeholder
	1,  // 13: rpc.TerwayTracing.GetResourceTypes:output_type -> rpc.ResourcesTypesReply
	2,  // 14: rpc.TerwayTracing.GetResources:output_type -> rpc.ResourcesNamesReply
	8,  // 15: rpc.TerwayTracing.GetResourceConfig:output_type -> rpc.ResourceConfigReply
	9,  // 16: rpc.TerwayTracing.GetResourceTrace:output_type -> rpc.ResourceTraceReply
	6,  // 17: rpc.TerwayTracing.ResourceExecute:output_type -> rpc.ResourceExecuteReply
	14, // 18: rpc.TerwayTracing.GetResourceMapping:output_type -> rpc.ResourceMappingReply
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init()                    { file_tracing_proto_init() }
func file_tracing_proto_init() { _ = "STUB: not implemented"; return }
