// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"

	ecs "github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"

	mock "github.com/stretchr/testify/mock"

	netip "net/netip"

	wait "k8s.io/apimachinery/pkg/util/wait"
)

// ECS is an autogenerated mock type for the ECS type
type ECS struct {
	mock.Mock
}

// AssignIpv6Addresses provides a mock function with given fields: ctx, opts
func (_m *ECS) AssignIpv6Addresses(ctx context.Context, opts ...client.AssignIPv6AddressesOption) ([]netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignIpv6Addresses2 provides a mock function with given fields: ctx, opts
func (_m *ECS) AssignIpv6Addresses2(ctx context.Context, opts ...client.AssignIPv6AddressesOption) ([]client.IPSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignPrivateIPAddress provides a mock function with given fields: ctx, opts
func (_m *ECS) AssignPrivateIPAddress(ctx context.Context, opts ...client.AssignPrivateIPAddressOption) ([]netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignPrivateIPAddress2 provides a mock function with given fields: ctx, opts
func (_m *ECS) AssignPrivateIPAddress2(ctx context.Context, opts ...client.AssignPrivateIPAddressOption) ([]client.IPSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachNetworkInterface provides a mock function with given fields: ctx, opts
func (_m *ECS) AttachNetworkInterface(ctx context.Context, opts ...client.AttachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateNetworkInterface provides a mock function with given fields: ctx, opts
func (_m *ECS) CreateNetworkInterface(ctx context.Context, opts ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNetworkInterface provides a mock function with given fields: ctx, eniID
func (_m *ECS) DeleteNetworkInterface(ctx context.Context, eniID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeInstanceTypes provides a mock function with given fields: ctx, types
func (_m *ECS) DescribeInstanceTypes(ctx context.Context, types []string) ([]ecs.InstanceType, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeNetworkInterface provides a mock function with given fields: ctx, vpcID, eniID, instanceID, instanceType, status, tags
func (_m *ECS) DescribeNetworkInterface(ctx context.Context, vpcID string, eniID []string, instanceID string, instanceType string, status string, tags map[string]string) ([]*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeNetworkInterface2 provides a mock function with given fields: ctx, opts
func (_m *ECS) DescribeNetworkInterface2(ctx context.Context, opts ...client.DescribeNetworkInterfaceOption) ([]*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeNetworkInterfaceAttribute provides a mock function with given fields: ctx, eniID
func (_m *ECS) DescribeNetworkInterfaceAttribute(ctx context.Context, eniID string) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachNetworkInterface provides a mock function with given fields: ctx, eniID, instanceID, trunkENIID
func (_m *ECS) DetachNetworkInterface(ctx context.Context, eniID string, instanceID string, trunkENIID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DetachNetworkInterface2 provides a mock function with given fields: ctx, opts
func (_m *ECS) DetachNetworkInterface2(ctx context.Context, opts ...client.DetachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignIpv6Addresses provides a mock function with given fields: ctx, eniID, ips
func (_m *ECS) UnAssignIpv6Addresses(ctx context.Context, eniID string, ips []netip.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignIpv6Addresses2 provides a mock function with given fields: ctx, eniID, ips
func (_m *ECS) UnAssignIpv6Addresses2(ctx context.Context, eniID string, ips []client.IPSet) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignPrivateIPAddresses provides a mock function with given fields: ctx, eniID, ips
func (_m *ECS) UnAssignPrivateIPAddresses(ctx context.Context, eniID string, ips []netip.Addr) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignPrivateIPAddresses2 provides a mock function with given fields: ctx, eniID, ips
func (_m *ECS) UnAssignPrivateIPAddresses2(ctx context.Context, eniID string, ips []client.IPSet) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitForNetworkInterface provides a mock function with given fields: ctx, eniID, status, backoff, ignoreNotExist
func (_m *ECS) WaitForNetworkInterface(ctx context.Context, eniID string, status string, backoff wait.Backoff, ignoreNotExist bool) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewECS creates a new instance of ECS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewECS(t interface {
	mock.TestingT
	Cleanup(func())
}) *ECS {
	_ = "STUB: not implemented"
	return nil
}
