// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"

	eflo "github.com/aliyun/alibaba-cloud-sdk-go/services/eflo"

	mock "github.com/stretchr/testify/mock"

	wait "k8s.io/apimachinery/pkg/util/wait"
)

// EFLO is an autogenerated mock type for the EFLO type
type EFLO struct {
	mock.Mock
}

// AssignLeniPrivateIPAddress2 provides a mock function with given fields: ctx, opts
func (_m *EFLO) AssignLeniPrivateIPAddress2(ctx context.Context, opts ...client.AssignPrivateIPAddressOption) ([]client.IPSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachHDENI provides a mock function with given fields: ctx, opts
func (_m *EFLO) AttachHDENI(ctx context.Context, opts ...client.AttachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// AttachLeni provides a mock function with given fields: ctx, opts
func (_m *EFLO) AttachLeni(ctx context.Context, opts ...client.AttachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateElasticNetworkInterfaceV2 provides a mock function with given fields: ctx, opts
func (_m *EFLO) CreateElasticNetworkInterfaceV2(ctx context.Context, opts ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateHDENI provides a mock function with given fields: ctx, opts
func (_m *EFLO) CreateHDENI(ctx context.Context, opts ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteElasticNetworkInterface provides a mock function with given fields: ctx, eniID
func (_m *EFLO) DeleteElasticNetworkInterface(ctx context.Context, eniID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteHDENI provides a mock function with given fields: ctx, eniID
func (_m *EFLO) DeleteHDENI(ctx context.Context, eniID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeHDENI provides a mock function with given fields: ctx, opts
func (_m *EFLO) DescribeHDENI(ctx context.Context, opts ...client.DescribeNetworkInterfaceOption) ([]*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeLeniNetworkInterface provides a mock function with given fields: ctx, opts
func (_m *EFLO) DescribeLeniNetworkInterface(ctx context.Context, opts ...client.DescribeNetworkInterfaceOption) ([]*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachHDENI provides a mock function with given fields: ctx, opts
func (_m *EFLO) DetachHDENI(ctx context.Context, opts ...client.DetachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// DetachLeni provides a mock function with given fields: ctx, opts
func (_m *EFLO) DetachLeni(ctx context.Context, opts ...client.DetachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// GetNodeInfoForPod provides a mock function with given fields: ctx, nodeID
func (_m *EFLO) GetNodeInfoForPod(ctx context.Context, nodeID string) (*eflo.Content, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListLeniPrivateIPAddresses provides a mock function with given fields: ctx, eniID, ipName, ipAddress
func (_m *EFLO) ListLeniPrivateIPAddresses(ctx context.Context, eniID string, ipName string, ipAddress string) (*eflo.Content, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnAssignLeniPrivateIPAddresses2 provides a mock function with given fields: ctx, eniID, ips
func (_m *EFLO) UnAssignLeniPrivateIPAddresses2(ctx context.Context, eniID string, ips []client.IPSet) error {
	_ = "STUB: not implemented"
	return nil
}

// UnassignLeniPrivateIPAddress provides a mock function with given fields: ctx, eniID, ipName
func (_m *EFLO) UnassignLeniPrivateIPAddress(ctx context.Context, eniID string, ipName string) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitForLeniNetworkInterface provides a mock function with given fields: ctx, eniID, status, backoff, ignoreNotExist
func (_m *EFLO) WaitForLeniNetworkInterface(ctx context.Context, eniID string, status string, backoff wait.Backoff, ignoreNotExist bool) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewEFLO creates a new instance of EFLO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEFLO(t interface {
	mock.TestingT
	Cleanup(func())
}) *EFLO {
	_ = "STUB: not implemented"
	return nil
}
