// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"

	mock "github.com/stretchr/testify/mock"
)

// EFLOControl is an autogenerated mock type for the EFLOControl type
type EFLOControl struct {
	mock.Mock
}

// DescribeNode provides a mock function with given fields: ctx, opts
func (_m *EFLOControl) DescribeNode(ctx context.Context, opts ...client.DescribeNodeRequestOption) (*client.DescribeNodeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeNodeType provides a mock function with given fields: ctx, opts
func (_m *EFLOControl) DescribeNodeType(ctx context.Context, opts ...client.DescribeNodeTypeRequestOption) (*client.DescribeNodeTypeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewEFLOControl creates a new instance of EFLOControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEFLOControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *EFLOControl {
	_ = "STUB: not implemented"
	return nil
}
