// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"
	mock "github.com/stretchr/testify/mock"
)

// LimitProvider is an autogenerated mock type for the LimitProvider type
type LimitProvider struct {
	mock.Mock
}

// GetLimit provides a mock function with given fields: _a0, instanceType
func (_m *LimitProvider) GetLimit(_a0 interface{}, instanceType string) (*client.Limits, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetLimitFromAnno provides a mock function with given fields: anno
func (_m *LimitProvider) GetLimitFromAnno(anno map[string]string) (*client.Limits, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewLimitProvider creates a new instance of LimitProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLimitProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *LimitProvider {
	_ = "STUB: not implemented"
	return nil
}
