// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/AliyunContainerService/terway/pkg/aliyun/client"

	mock "github.com/stretchr/testify/mock"

	wait "k8s.io/apimachinery/pkg/util/wait"
)

// OpenAPI is an autogenerated mock type for the OpenAPI type
type OpenAPI struct {
	mock.Mock
}

// AssignIpv6AddressesV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) AssignIpv6AddressesV2(ctx context.Context, opts ...client.AssignIPv6AddressesOption) ([]client.IPSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignPrivateIPAddressV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) AssignPrivateIPAddressV2(ctx context.Context, opts ...client.AssignPrivateIPAddressOption) ([]client.IPSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AttachNetworkInterfaceV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) AttachNetworkInterfaceV2(ctx context.Context, opts ...client.AttachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateNetworkInterfaceV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) CreateNetworkInterfaceV2(ctx context.Context, opts ...client.CreateNetworkInterfaceOption) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNetworkInterfaceV2 provides a mock function with given fields: ctx, eniID
func (_m *OpenAPI) DeleteNetworkInterfaceV2(ctx context.Context, eniID string) error {
	_ = "STUB: not implemented"
	return nil
}

// DescribeNetworkInterfaceV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) DescribeNetworkInterfaceV2(ctx context.Context, opts ...client.DescribeNetworkInterfaceOption) ([]*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DetachNetworkInterfaceV2 provides a mock function with given fields: ctx, opts
func (_m *OpenAPI) DetachNetworkInterfaceV2(ctx context.Context, opts ...client.DetachNetworkInterfaceOption) error {
	_ = "STUB: not implemented"
	return nil
}

// GetECS provides a mock function with no fields
func (_m *OpenAPI) GetECS() client.ECS { _ = "STUB: not implemented"; return *new(client.ECS) }

// GetEFLO provides a mock function with no fields
func (_m *OpenAPI) GetEFLO() client.EFLO { _ = "STUB: not implemented"; return *new(client.EFLO) }

// GetEFLOController provides a mock function with no fields
func (_m *OpenAPI) GetEFLOController() client.EFLOControl {
	_ = "STUB: not implemented"
	return *new(client.EFLOControl)
}

// GetVPC provides a mock function with no fields
func (_m *OpenAPI) GetVPC() client.VPC { _ = "STUB: not implemented"; return *new(client.VPC) }

// UnAssignIpv6AddressesV2 provides a mock function with given fields: ctx, eniID, ips
func (_m *OpenAPI) UnAssignIpv6AddressesV2(ctx context.Context, eniID string, ips []client.IPSet) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignPrivateIPAddressesV2 provides a mock function with given fields: ctx, eniID, ips
func (_m *OpenAPI) UnAssignPrivateIPAddressesV2(ctx context.Context, eniID string, ips []client.IPSet) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitForNetworkInterfaceV2 provides a mock function with given fields: ctx, eniID, status, backoff, ignoreNotExist
func (_m *OpenAPI) WaitForNetworkInterfaceV2(ctx context.Context, eniID string, status string, backoff wait.Backoff, ignoreNotExist bool) (*client.NetworkInterface, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewOpenAPI creates a new instance of OpenAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenAPI {
	_ = "STUB: not implemented"
	return nil
}
