// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	vpc "github.com/aliyun/alibaba-cloud-sdk-go/services/vpc"
	mock "github.com/stretchr/testify/mock"
)

// VPC is an autogenerated mock type for the VPC type
type VPC struct {
	mock.Mock
}

// DescribeVSwitchByID provides a mock function with given fields: ctx, vSwitchID
func (_m *VPC) DescribeVSwitchByID(ctx context.Context, vSwitchID string) (*vpc.VSwitch, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewVPC creates a new instance of VPC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVPC(t interface {
	mock.TestingT
	Cleanup(func())
}) *VPC {
	_ = "STUB: not implemented"
	return nil
}
