// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *Storage) Delete(key string) error { _ = "STUB: not implemented"; return nil }

// Get provides a mock function with given fields: key
func (_m *Storage) Get(key string) (interface{}, error) { _ = "STUB: not implemented"; return nil, nil }

// List provides a mock function with no fields
func (_m *Storage) List() ([]interface{}, error) { _ = "STUB: not implemented"; return nil, nil }

// Put provides a mock function with given fields: key, value
func (_m *Storage) Put(key string, value interface{}) error { _ = "STUB: not implemented"; return nil }

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	_ = "STUB: not implemented"
	return nil
}
