// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// GetInstanceID provides a mock function with no fields
func (_m *Interface) GetInstanceID() (string, error) { _ = "STUB: not implemented"; return "", nil }

// GetInstanceType provides a mock function with no fields
func (_m *Interface) GetInstanceType() (string, error) { _ = "STUB: not implemented"; return "", nil }

// GetPrimaryMAC provides a mock function with no fields
func (_m *Interface) GetPrimaryMAC() (string, error) { _ = "STUB: not implemented"; return "", nil }

// GetRegionID provides a mock function with no fields
func (_m *Interface) GetRegionID() (string, error) { _ = "STUB: not implemented"; return "", nil }

// GetVSwitchID provides a mock function with no fields
func (_m *Interface) GetVSwitchID() (string, error) { _ = "STUB: not implemented"; return "", nil }

// GetZoneID provides a mock function with no fields
func (_m *Interface) GetZoneID() (string, error) { _ = "STUB: not implemented"; return "", nil }

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	_ = "STUB: not implemented"
	return nil
}
