// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	client "sigs.k8s.io/controller-runtime/pkg/client"

	daemon "github.com/AliyunContainerService/terway/types/daemon"

	mock "github.com/stretchr/testify/mock"

	rest "k8s.io/client-go/rest"

	types "github.com/AliyunContainerService/terway/types"

	v1 "k8s.io/api/core/v1"
)

// Kubernetes is an autogenerated mock type for the Kubernetes type
type Kubernetes struct {
	mock.Mock
}

// GetClient provides a mock function with no fields
func (_m *Kubernetes) GetClient() client.Client {
	_ = "STUB: not implemented"
	return *new(client.Client)
}

// GetDynamicConfigWithName provides a mock function with given fields: ctx, name
func (_m *Kubernetes) GetDynamicConfigWithName(ctx context.Context, name string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetLocalPods provides a mock function with given fields: ctx
func (_m *Kubernetes) GetLocalPods(ctx context.Context) ([]*daemon.PodInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNodeDynamicConfigLabel provides a mock function with no fields
func (_m *Kubernetes) GetNodeDynamicConfigLabel() string { _ = "STUB: not implemented"; return "" }

// GetPod provides a mock function with given fields: ctx, namespace, name, cache
func (_m *Kubernetes) GetPod(ctx context.Context, namespace string, name string, cache bool) (*daemon.PodInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetRestConfig provides a mock function with no fields
func (_m *Kubernetes) GetRestConfig() *rest.Config { _ = "STUB: not implemented"; return nil }

// GetServiceCIDR provides a mock function with no fields
func (_m *Kubernetes) GetServiceCIDR() *types.IPNetSet { _ = "STUB: not implemented"; return nil }

// GetTrunkID provides a mock function with no fields
func (_m *Kubernetes) GetTrunkID() string { _ = "STUB: not implemented"; return "" }

// Node provides a mock function with no fields
func (_m *Kubernetes) Node() *v1.Node { _ = "STUB: not implemented"; return nil }

// NodeName provides a mock function with no fields
func (_m *Kubernetes) NodeName() string { _ = "STUB: not implemented"; return "" }

// PatchNodeAnnotations provides a mock function with given fields: ctx, anno
func (_m *Kubernetes) PatchNodeAnnotations(ctx context.Context, anno map[string]string) error {
	_ = "STUB: not implemented"
	return nil
}

// PatchNodeIPResCondition provides a mock function with given fields: status, reason, message
func (_m *Kubernetes) PatchNodeIPResCondition(status v1.ConditionStatus, reason string, message string) error {
	_ = "STUB: not implemented"
	return nil
}

// PatchPodIPInfo provides a mock function with given fields: ctx, info, ips
func (_m *Kubernetes) PatchPodIPInfo(ctx context.Context, info *daemon.PodInfo, ips string) error {
	_ = "STUB: not implemented"
	return nil
}

// PodExist provides a mock function with given fields: ctx, namespace, name
func (_m *Kubernetes) PodExist(ctx context.Context, namespace string, name string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// RecordNodeEvent provides a mock function with given fields: eventType, reason, message
func (_m *Kubernetes) RecordNodeEvent(eventType string, reason string, message string) {
	_ = "STUB: not implemented"
	return
}

// RecordPodEvent provides a mock function with given fields: podName, podNamespace, eventType, reason, message
func (_m *Kubernetes) RecordPodEvent(podName string, podNamespace string, eventType string, reason string, message string) error {
	_ = "STUB: not implemented"
	return nil
}

// SetCustomStatefulWorkloadKinds provides a mock function with given fields: kinds
func (_m *Kubernetes) SetCustomStatefulWorkloadKinds(kinds []string) error {
	_ = "STUB: not implemented"
	return nil
}

// SetNodeAllocatablePod provides a mock function with given fields: count
func (_m *Kubernetes) SetNodeAllocatablePod(count int) error { _ = "STUB: not implemented"; return nil }

// NewKubernetes creates a new instance of Kubernetes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKubernetes(t interface {
	mock.TestingT
	Cleanup(func())
}) *Kubernetes {
	_ = "STUB: not implemented"
	return nil
}
