// Code generated by "stringer -type=ConditionType -trimprefix=Condition"; DO NOT EDIT.

package eni

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _ConditionType_name = "FullResourceTypeMismatchNetworkInterfaceMismatchInsufficientVSwitchIP"

var _ConditionType_index = [...]uint8{0, 4, 24, 48, 69}

func (i ConditionType) String() string { _ = "STUB: not implemented"; return "" }
