// Code generated by "stringer -type=eniStatus -trimprefix=status"; DO NOT EDIT.

package eni

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _eniStatus_name = "InitCreatingInUseDeleting"

var _eniStatus_index = [...]uint8{0, 4, 12, 17, 25}

func (i eniStatus) String() string { _ = "STUB: not implemented"; return "" }
