// Code generated by "stringer -type=ipStatus -trimprefix=ipStatus"; DO NOT EDIT.

package eni

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _ipStatus_name = "InitValidInvalidDeleting"

var _ipStatus_index = [...]uint8{0, 4, 9, 16, 24}

func (i ipStatus) String() string { _ = "STUB: not implemented"; return "" }
