// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NodeCapabilitiesStore is an autogenerated mock type for the NodeCapabilitiesStore type
type NodeCapabilitiesStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: capName
func (_m *NodeCapabilitiesStore) Get(capName string) string { _ = "STUB: not implemented"; return "" }

// Load provides a mock function with no fields
func (_m *NodeCapabilitiesStore) Load() error { _ = "STUB: not implemented"; return nil }

// Save provides a mock function with no fields
func (_m *NodeCapabilitiesStore) Save() error { _ = "STUB: not implemented"; return nil }

// Set provides a mock function with given fields: capName, value
func (_m *NodeCapabilitiesStore) Set(capName string, value string) {
	_ = "STUB: not implemented"
	return
}

// NewNodeCapabilitiesStore creates a new instance of NodeCapabilitiesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeCapabilitiesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeCapabilitiesStore {
	_ = "STUB: not implemented"
	return nil
}
