// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	daemon "github.com/AliyunContainerService/terway/types/daemon"

	mock "github.com/stretchr/testify/mock"

	netip "net/netip"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// AssignNIPv4 provides a mock function with given fields: eniID, count, mac
func (_m *Factory) AssignNIPv4(eniID string, count int, mac string) ([]netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssignNIPv6 provides a mock function with given fields: eniID, count, mac
func (_m *Factory) AssignNIPv6(eniID string, count int, mac string) ([]netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateNetworkInterface provides a mock function with given fields: ipv4, ipv6, eniType
func (_m *Factory) CreateNetworkInterface(ipv4 int, ipv6 int, eniType string) (*daemon.ENI, []netip.Addr, []netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// DeleteNetworkInterface provides a mock function with given fields: eniID
func (_m *Factory) DeleteNetworkInterface(eniID string) error {
	_ = "STUB: not implemented"
	return nil
}

// GetAttachedNetworkInterface provides a mock function with given fields: preferTrunkID
func (_m *Factory) GetAttachedNetworkInterface(preferTrunkID string) ([]*daemon.ENI, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LoadNetworkInterface provides a mock function with given fields: mac
func (_m *Factory) LoadNetworkInterface(mac string) ([]netip.Addr, []netip.Addr, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// UnAssignNIPv4 provides a mock function with given fields: eniID, ips, mac
func (_m *Factory) UnAssignNIPv4(eniID string, ips []netip.Addr, mac string) error {
	_ = "STUB: not implemented"
	return nil
}

// UnAssignNIPv6 provides a mock function with given fields: eniID, ips, mac
func (_m *Factory) UnAssignNIPv6(eniID string, ips []netip.Addr, mac string) error {
	_ = "STUB: not implemented"
	return nil
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	_ = "STUB: not implemented"
	return nil
}
